config/routes.rb
class MarketingListConstraint
  def initialize
    @ips = RestrictedList.retrieve_ips
  end

  def matches?(request)
    @ips.include?(request.host)
  end
end

Rails.application.routes.draw do
  constraints(MarketingListConstraint.new) do
    scope module: "marketing" do
      get "/sign_up", to: "accounts#new"
      post "/sign_up", to: "accounts#create"

      get "/themes/desert", to: "themes#desert"
      get "/themes/links", to: "themes#links"
      get "/themes/parkland", to: "themes#parkland"

      get "/", to: "home#index", as: "marketing_home"
    end
  end

  namespace :admin do
    get "/", to: "dashboard#index", as: :root

    resources :enquiries do
      member do
        put "open"
        put "close"
      end
    end
    resources :enquiry_forms
    resource :footers, only: [:edit, :update]
    resources :headers, only: %i[edit update]
    resources :posts
    resources :websites, only: %i[edit update]
  end

  resources :enquiries, only: :create
  resources :posts, only: %i[show]

  root "home#index"
end

app/controllers/admin/enquiry_forms_controller.rb
module Admin
  class EnquiryFormsController < BaseController
    def index
      @enquiry_forms = @current_website.enquiry_forms
    end

    def new
      @enquiry_form = @current_website.enquiry_forms.new
    end

    def create
      @enquiry_form = @current_website.enquiry_forms.new(enquiry_form_params)
      if @enquiry_form.update(enquiry_form_params)
        set_default_enquiry_form
        redirect_to admin_enquiry_forms_path, success: t(".success")
      else
        render :new
      end
    end

    def edit
      @enquiry_form = @current_website.enquiry_forms.find(params[:id])
    end

    def update
      @enquiry_form = @current_website.enquiry_forms.find(params[:id])
      if @enquiry_form.update(enquiry_form_params)
        set_default_enquiry_form
        redirect_to admin_enquiry_forms_path, success: t(".success")
      else
        render :edit
      end
    end

    def destroy
      @current_website.enquiry_forms.find(params[:id]).destroy
      redirect_to admin_enquiry_forms_path, success: t(".success")
    end

    private

    def enquiry_form_params
      params
        .require(:enquiry_form)
        .permit(:title, :introduction, :success_message, :active, :default_form)
    end

    def set_default_enquiry_form
      if @enquiry_form.default_form?
        @enquiry_form.website.enquiry_forms.where.not(id: @enquiry_form.id).update_all(default_form: false)
      end
    end
  end
end

app/views/admin/enquiry_forms/edit.html.erb
<% content_for(:title, "Enquiry Forms") %>

<%= form_with(model: [:admin, @enquiry_form], local: true, multipart: true, class: "space-y-8", data: {turbo: false}) do |form| %>
  <div class="px-4 py-5 bg-white shadow sm:rounded-lg sm:p-6">
    <div class="md:grid md:grid-cols-3 md:gap-6">
      <div class="md:col-span-1">
        <%= render partial: "shared/section_title", locals: { title: t(".essentials.title"), description: t(".essentials.description") } %>
      </div>
      <div class="mt-5 md:mt-0 md:col-span-2">
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-4 space-y-2">
            <%= render(Admin::ErrorMessageComponent.new(resource: @enquiry_form, attributes: [:title, :introduction, :success_message])) %>
          </div>

          <div class="col-span-4 space-y-2">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :title)) %>
            <div class="mt-1">
              <%= form.text_field :title, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500" %>
            </div>
          </div>

          <div class="col-span-4 space-y-2">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :introduction)) %>
            <div class="mt-1">
              <%= form.text_field :introduction, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500" %>
            </div>
          </div>

          <div class="col-span-4 space-y-2">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :success_message)) %>
            <div class="mt-1">
              <%= form.text_field :success_message, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500" %>
            </div>
          </div>

          <div class="col-span-4 space-y-2" x-data="{ <%= form.object.active? ? "on: true" : "on: false" %> }">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :active)) %>
            <div class="mt-1">
              <%= form.hidden_field :active, { "x-model" => "on" } %>
              <button
                type="button"
                class="relative inline-flex flex-shrink-0 h-6 transition-colors duration-200 ease-in-out bg-gray-400 border-2 border-transparent rounded-full cursor-pointer w-11 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                :class="{ 'bg-green-600': on, 'bg-gray-200': !(on) }"
                aria-pressed="false"
                :aria-pressed="on.toString()"
                @click="on = !on"
                x-state:on="Enabled"
                x-state:off="Not Enabled"
              >
                <span class="sr-only">
                  Turn on enquiry form?
                </span>

                <span
                  class="relative inline-block w-5 h-5 transition duration-200 ease-in-out transform translate-x-0 bg-white rounded-full shadow pointer-events-none ring-0"
                  x-state:on="Enabled"
                  x-state:off="Not Enabled"
                  :class="{ 'translate-x-5': on, 'translate-x-0': !(on) }"
                >
                  <span
                    class="absolute inset-0 flex items-center justify-center w-full h-full transition-opacity duration-200 ease-in opacity-100"
                    aria-hidden="true"
                    x-state:on="Enabled"
                    x-state:off="Not Enabled"
                    :class="{ 'opacity-0 ease-out duration-100': on, 'opacity-100 ease-in duration-200': !(on) }"
                  >
                    <svg class="w-3 h-3 text-gray-600 bg-white" fill="none" viewBox="0 0 12 12">
                      <path d="M4 8l2-2m0 0l2-2M6 6L4 4m2 2l2 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                  </span>

                  <span
                    class="absolute inset-0 flex items-center justify-center w-full h-full transition-opacity duration-100 ease-out opacity-0"
                    aria-hidden="true"
                    x-state:on="Enabled"
                    x-state:off="Not Enabled"
                    :class="{ 'opacity-100 ease-in duration-200': on, 'opacity-0 ease-out duration-100': !(on) }"
                  >
                    <svg class="w-3 h-3 text-blue-600 bg-white" fill="currentColor" viewBox="0 0 12 12">
                      <path d="M3.707 5.293a1 1 0 00-1.414 1.414l1.414-1.414zM5 8l-.707.707a1 1 0 001.414 0L5 8zm4.707-3.293a1 1 0 00-1.414-1.414l1.414 1.414zm-7.414 2l2 2 1.414-1.414-2-2-1.414 1.414zm3.414 2l4-4-1.414-1.414-4 4 1.414 1.414z"></path>
                    </svg>
                  </span>
                </span>
              </button>
            </div>
          </div>

          <div class="col-span-4 space-y-2" x-data="{ <%= form.object.default_form? ? "on: true" : "on: false" %> }">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :default_form)) %>
            <div class="mt-1">
              <%= form.hidden_field :default_form, { "x-model" => "on" } %>
              <button
                type="button"
                class="relative inline-flex flex-shrink-0 h-6 transition-colors duration-200 ease-in-out bg-gray-400 border-2 border-transparent rounded-full cursor-pointer w-11 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                :class="{ 'bg-green-600': on, 'bg-gray-200': !(on) }"
                aria-pressed="false"
                :aria-pressed="on.toString()"
                @click="on = !on"
                x-state:on="Enabled"
                x-state:off="Not Enabled"
              >
                <span class="sr-only">
                  Default form for website
                </span>

                <span
                  class="relative inline-block w-5 h-5 transition duration-200 ease-in-out transform translate-x-0 bg-white rounded-full shadow pointer-events-none ring-0"
                  x-state:on="Enabled"
                  x-state:off="Not Enabled"
                  :class="{ 'translate-x-5': on, 'translate-x-0': !(on) }"
                >
                  <span
                    class="absolute inset-0 flex items-center justify-center w-full h-full transition-opacity duration-200 ease-in opacity-100"
                    aria-hidden="true"
                    x-state:on="Enabled"
                    x-state:off="Not Enabled"
                    :class="{ 'opacity-0 ease-out duration-100': on, 'opacity-100 ease-in duration-200': !(on) }"
                  >
                    <svg class="w-3 h-3 text-gray-600 bg-white" fill="none" viewBox="0 0 12 12">
                      <path d="M4 8l2-2m0 0l2-2M6 6L4 4m2 2l2 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                  </span>

                  <span
                    class="absolute inset-0 flex items-center justify-center w-full h-full transition-opacity duration-100 ease-out opacity-0"
                    aria-hidden="true"
                    x-state:on="Enabled"
                    x-state:off="Not Enabled"
                    :class="{ 'opacity-100 ease-in duration-200': on, 'opacity-0 ease-out duration-100': !(on) }"
                  >
                    <svg class="w-3 h-3 text-blue-600 bg-white" fill="currentColor" viewBox="0 0 12 12">
                      <path d="M3.707 5.293a1 1 0 00-1.414 1.414l1.414-1.414zM5 8l-.707.707a1 1 0 001.414 0L5 8zm4.707-3.293a1 1 0 00-1.414-1.414l1.414 1.414zm-7.414 2l2 2 1.414-1.414-2-2-1.414 1.414zm3.414 2l4-4-1.414-1.414-4 4 1.414 1.414z"></path>
                    </svg>
                  </span>
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="flex justify-end">
    <%= form.submit t(".submit"), class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
  </div>
<% end %>

app/views/admin/enquiry_forms/index.html.erb
<% content_for(:title, "Enquiry Forms") %>

<div class="sm:flex sm:items-center">
  <div class="sm:flex-auto">
  </div>
  <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
    <% if @current_website.subscribed? %>
      <%= link_to("Add Enquiry Form", new_admin_enquiry_form_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 sm:w-auto")%>
    <% end %>
  </div>
</div>
<div class="flex flex-col mt-8">
  <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
      <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
        <table class="min-w-full divide-y divide-gray-300">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3 pl-4 pr-3 text-xs font-medium tracking-wide text-left text-gray-500 uppercase sm:pl-6">Title</th>
              <th scope="col" class="px-3 py-3 text-xs font-medium tracking-wide text-left text-gray-500 uppercase">Active</th>
              <th scope="col" class="px-3 py-3 text-xs font-medium tracking-wide text-left text-gray-500 uppercase">Default Form</th>
              <th scope="col" class="relative py-3 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Actions</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @current_website.enquiry_forms.each do |e| %>
              <tr id="<%= "enquiry_form_#{e.id}" %>">
                <td id="<%= "enquiry_form_#{e.id}_title" %>" class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 whitespace-nowrap sm:pl-6">
                  <%= e.title %>
                </td>
                <td id="<%= "enquiry_form_#{e.id}_active" %>" class="px-3 py-4 text-sm text-gray-500 whitespace-nowrap">
                  <% if e.active? %>
                    <span class="inline-flex px-2 py-1 text-xs font-semibold leading-5 text-green-800 bg-green-100 rounded-full">Active</span>
                  <% end %>
                </td>
                <td id="<%= "enquiry_form_#{e.id}_default_form" %>" class="px-3 py-4 text-sm text-gray-500 whitespace-nowrap">
                  <% if e.default_form? %>
                    <span class="inline-flex px-2 py-1 text-xs font-semibold leading-5 text-gray-800 bg-gray-100 rounded-full">Default form</span>
                  <% end %>
                </td>
                <td class="flex items-center justify-end space-x-6 py-4 pl-3 pr-4 text-sm font-medium text-right whitespace-nowrap sm:pr-6">
                  <%= link_to("Edit", edit_admin_enquiry_form_path(e), class: "text-blue-600 hover:text-blue-900") %>

                  <% #TODO: Add a confirmation modal for deleting enquiry form %>
                  <% if @current_website.subscribed? %>
                    <%= button_to(admin_enquiry_form_path(e), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'bg-red-500 hover:bg-red-600 text-white p-1 rounded', form_class: '') do %>
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                        <path fill-rule="evenodd" d="M8.75 1A2.75 2.75 0 006 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 10.23 1.482l.149-.022.841 10.518A2.75 2.75 0 007.596 19h4.807a2.75 2.75 0 002.742-2.53l.841-10.52.149.023a.75.75 0 00.23-1.482A41.03 41.03 0 0014 4.193V3.75A2.75 2.75 0 0011.25 1h-2.5zM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4zM8.58 7.72a.75.75 0 00-1.5.06l.3 7.5a.75.75 0 101.5-.06l-.3-7.5zm4.34.06a.75.75 0 10-1.5-.06l-.3 7.5a.75.75 0 101.5.06l.3-7.5z" clip-rule="evenodd" />
                      </svg>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/enquiry_forms/new.html.erb
<% content_for(:title, "Enquiry Forms") %>

<%= form_with(model: [:admin, @enquiry_form], local: true, multipart: true, class: "space-y-8", data: { turbo: false }) do |form| %>
  <div class="px-4 py-5 bg-white shadow sm:rounded-lg sm:p-6">
    <div class="md:grid md:grid-cols-3 md:gap-6">
      <div class="md:col-span-1">
        <%= render partial: "shared/section_title", locals: { title: t(".essentials.title"), description: t(".essentials.description") } %>
      </div>
      <div class="mt-5 md:mt-0 md:col-span-2">
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-4 space-y-2">
            <%= render(Admin::ErrorMessageComponent.new(resource: @enquiry_form, attributes: [:title, :introduction, :success_message])) %>
          </div>

          <div class="col-span-4 space-y-2">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :title)) %>
            <div class="mt-1">
              <%= form.text_field :title, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500" %>
            </div>
          </div>

          <div class="col-span-4 space-y-2">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :introduction)) %>
            <div class="mt-1">
              <%= form.text_field :introduction, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500" %>
            </div>
          </div>

          <div class="col-span-4 space-y-2">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :success_message)) %>
            <div class="mt-1">
              <%= form.text_field :success_message, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500" %>
            </div>
          </div>

          <div class="col-span-4 space-y-2" x-data="{ <%= form.object.active? ? "on: true" : "on: false" %> }">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :active)) %>
            <div class="mt-1">
              <%= form.hidden_field :active, { "x-model" => "on" } %>
              <button
                type="button"
                class="relative inline-flex flex-shrink-0 h-6 transition-colors duration-200 ease-in-out bg-gray-400 border-2 border-transparent rounded-full cursor-pointer w-11 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                :class="{ 'bg-green-600': on, 'bg-gray-200': !(on) }"
                aria-pressed="false"
                :aria-pressed="on.toString()"
                @click="on = !on"
                x-state:on="Enabled"
                x-state:off="Not Enabled"
              >
                <span class="sr-only">
                  Turn on enquiry form?
                </span>

                <span
                  class="relative inline-block w-5 h-5 transition duration-200 ease-in-out transform translate-x-0 bg-white rounded-full shadow pointer-events-none ring-0"
                  x-state:on="Enabled"
                  x-state:off="Not Enabled"
                  :class="{ 'translate-x-5': on, 'translate-x-0': !(on) }"
                >
                  <span
                    class="absolute inset-0 flex items-center justify-center w-full h-full transition-opacity duration-200 ease-in opacity-100"
                    aria-hidden="true"
                    x-state:on="Enabled"
                    x-state:off="Not Enabled"
                    :class="{ 'opacity-0 ease-out duration-100': on, 'opacity-100 ease-in duration-200': !(on) }"
                  >
                    <svg class="w-3 h-3 text-gray-600 bg-white" fill="none" viewBox="0 0 12 12">
                      <path d="M4 8l2-2m0 0l2-2M6 6L4 4m2 2l2 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                  </span>

                  <span
                    class="absolute inset-0 flex items-center justify-center w-full h-full transition-opacity duration-100 ease-out opacity-0"
                    aria-hidden="true"
                    x-state:on="Enabled"
                    x-state:off="Not Enabled"
                    :class="{ 'opacity-100 ease-in duration-200': on, 'opacity-0 ease-out duration-100': !(on) }"
                  >
                    <svg class="w-3 h-3 text-blue-600 bg-white" fill="currentColor" viewBox="0 0 12 12">
                      <path d="M3.707 5.293a1 1 0 00-1.414 1.414l1.414-1.414zM5 8l-.707.707a1 1 0 001.414 0L5 8zm4.707-3.293a1 1 0 00-1.414-1.414l1.414 1.414zm-7.414 2l2 2 1.414-1.414-2-2-1.414 1.414zm3.414 2l4-4-1.414-1.414-4 4 1.414 1.414z"></path>
                    </svg>
                  </span>
                </span>
              </button>
            </div>
          </div>

          <div class="col-span-4 space-y-2" x-data="{ <%= form.object.default_form? ? "on: true" : "on: false" %> }">
            <%= render(Admin::FormLabelComponent.new(form: form, attribute: :default_form)) %>
            <div class="mt-1">
              <%= form.hidden_field :default_form, { "x-model" => "on" } %>
              <button
                type="button"
                class="relative inline-flex flex-shrink-0 h-6 transition-colors duration-200 ease-in-out bg-gray-400 border-2 border-transparent rounded-full cursor-pointer w-11 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                :class="{ 'bg-green-600': on, 'bg-gray-200': !(on) }"
                aria-pressed="false"
                :aria-pressed="on.toString()"
                @click="on = !on"
                x-state:on="Enabled"
                x-state:off="Not Enabled"
              >
                <span class="sr-only">
                  Default form for website
                </span>

                <span
                  class="relative inline-block w-5 h-5 transition duration-200 ease-in-out transform translate-x-0 bg-white rounded-full shadow pointer-events-none ring-0"
                  x-state:on="Enabled"
                  x-state:off="Not Enabled"
                  :class="{ 'translate-x-5': on, 'translate-x-0': !(on) }"
                >
                  <span
                    class="absolute inset-0 flex items-center justify-center w-full h-full transition-opacity duration-200 ease-in opacity-100"
                    aria-hidden="true"
                    x-state:on="Enabled"
                    x-state:off="Not Enabled"
                    :class="{ 'opacity-0 ease-out duration-100': on, 'opacity-100 ease-in duration-200': !(on) }"
                  >
                    <svg class="w-3 h-3 text-gray-600 bg-white" fill="none" viewBox="0 0 12 12">
                      <path d="M4 8l2-2m0 0l2-2M6 6L4 4m2 2l2 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                  </span>

                  <span
                    class="absolute inset-0 flex items-center justify-center w-full h-full transition-opacity duration-100 ease-out opacity-0"
                    aria-hidden="true"
                    x-state:on="Enabled"
                    x-state:off="Not Enabled"
                    :class="{ 'opacity-100 ease-in duration-200': on, 'opacity-0 ease-out duration-100': !(on) }"
                  >
                    <svg class="w-3 h-3 text-blue-600 bg-white" fill="currentColor" viewBox="0 0 12 12">
                      <path d="M3.707 5.293a1 1 0 00-1.414 1.414l1.414-1.414zM5 8l-.707.707a1 1 0 001.414 0L5 8zm4.707-3.293a1 1 0 00-1.414-1.414l1.414 1.414zm-7.414 2l2 2 1.414-1.414-2-2-1.414 1.414zm3.414 2l4-4-1.414-1.414-4 4 1.414 1.414z"></path>
                    </svg>
                  </span>
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="flex justify-end">
    <%= form.submit t(".submit"), class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
  </div>
<% end %>