config/routes.rb
class MarketingListConstraint
  def initialize
    @ips = RestrictedList.retrieve_ips
  end

  def matches?(request)
    @ips.include?(request.host)
  end
end

Rails.application.routes.draw do
  constraints(MarketingListConstraint.new) do
    scope module: "marketing" do
      get "/sign_up", to: "accounts#new"
      post "/sign_up", to: "accounts#create"

      get "/themes/desert", to: "themes#desert"
      get "/themes/links", to: "themes#links"
      get "/themes/parkland", to: "themes#parkland"

      get "/", to: "home#index", as: "marketing_home"
    end
  end

  namespace :admin do
    get "/", to: "dashboard#index", as: :root

    resources :enquiries do
      member do
        put "open"
        put "close"
      end
    end
    resources :enquiry_forms
    resource :footers, only: [:edit, :update]
    resources :headers, only: %i[edit update]
    resources :posts
    resources :websites, only: %i[edit update]
  end

  resources :enquiries, only: :create
  resources :posts, only: %i[show]

  root "home#index"
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < BaseController
    def index
      @open_enquiries = @current_website.enquiries.open
    end
  end
end

app/views/admin/dashboard/index.html.erb
<% content_for(:title, "Dashboard") %>

<div>
  <dl class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
    <div class="relative overflow-hidden rounded-lg bg-white px-4 pt-5 pb-12 shadow sm:px-6 sm:pt-6">
      <dt>
        <div class="absolute rounded-md bg-blue-500 p-3">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="flex-shrink-0 w-6 h-6 text-white">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 3.75H6.912a2.25 2.25 0 00-2.15 1.588L2.35 13.177a2.25 2.25 0 00-.1.661V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18v-4.162c0-.224-.034-.447-.1-.661L19.24 5.338a2.25 2.25 0 00-2.15-1.588H15M2.25 13.5h3.86a2.25 2.25 0 012.012 1.244l.256.512a2.25 2.25 0 002.013 1.244h3.218a2.25 2.25 0 002.013-1.244l.256-.512a2.25 2.25 0 012.013-1.244h3.859M12 3v8.25m0 0l-3-3m3 3l3-3" />
          </svg>
        </div>
        <p class="ml-16 truncate text-sm font-medium text-gray-500">Open Enquiries</p>
      </dt>
      <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
        <p class="text-2xl font-semibold text-gray-900">
          <%= @open_enquiries.length %>
        </p>
        <div class="absolute inset-x-0 bottom-0 bg-gray-50 px-4 py-4 sm:px-6">
          <div class="text-sm">
            <%= link_to "View all open enquiries", admin_enquiries_path, class: "font-medium text-blue-600 hover:text-blue-500" %>
          </div>
        </div>
      </dd>
    </div>
  </dl>
</div>