config/routes.rb
class MarketingListConstraint
  def initialize
    @ips = RestrictedList.retrieve_ips
  end

  def matches?(request)
    @ips.include?(request.host)
  end
end

Rails.application.routes.draw do
  constraints(MarketingListConstraint.new) do
    scope module: "marketing" do
      get "/sign_up", to: "accounts#new"
      post "/sign_up", to: "accounts#create"

      get "/themes/desert", to: "themes#desert"
      get "/themes/links", to: "themes#links"
      get "/themes/parkland", to: "themes#parkland"

      get "/", to: "home#index", as: "marketing_home"
    end
  end

  namespace :admin do
    get "/", to: "dashboard#index", as: :root

    resources :enquiries do
      member do
        put "open"
        put "close"
      end
    end
    resources :enquiry_forms
    resource :footers, only: [:edit, :update]
    resources :headers, only: %i[edit update]
    resources :posts
    resources :websites, only: %i[edit update]
  end

  resources :enquiries, only: :create
  resources :posts, only: %i[show]

  root "home#index"
end

app/models/account.rb
class Account < ApplicationRecord
  attr_accessor :subdomain

  has_many :websites, validate: false

  validates :name, presence: true, uniqueness: true
  validates :subdomain, format: {with: /[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?/, message: "is invalid"}
  validate :subdomain_is_unique

  def self.new_with_website(account_params)
    account = Account.new(account_params)
    account.websites.build(name: account.name, subdomain: account.subdomain)

    account
  end

  def subdomain_is_unique
    if subdomain.present? && Website.find_by(subdomain: subdomain).present?
      errors.add(:subdomain, "has already been taken")
    end
  end
end

app/controllers/marketing/accounts_controller.rb
module Marketing
  class AccountsController < ApplicationController
    def def new
      @account = Account.new
    end

    def create
      account = Account.new_with_website(account_params)

      if account.save
        website_url = account.websites.first.host_url(platform_host)
        redirect_to website_url, allow_other_host: true
      else
        @account = account
        render :new, status: :unprocessable_entity
      end
    end

    private

    def account_params
      params.require(:account).permit(:name, :subdomain)
    end
  end
end

app/controllers/marketing/home_controller.rb
module Marketing
  class HomeController < ApplicationController
    def index
    end
  end
end

app/controllers/marketing/themes_controller.rb
require "faker"

module Marketing
  class ThemesController < ApplicationController
    layout "theme"

    def desert
      @theme = "desert"
      @website = Website.find_by(subdomain: "mapleshore")
    end

    def links
      @theme = "links"
      @website = Website.find_by(subdomain: "mapleshore")
    end

    def parkland
      @theme = "parkland"
      @website = Website.find_by(subdomain: "mapleshore")
    end
  end
end

app/views/marketing/accounts/_form.html.erb
<div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <h2 class="mt-6 text-center text-3xl tracking-tight font-bold text-gray-900">
      <%= t(".title") %>
    </h2>
  </div>

  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with model: @account, scope: :account, url: sign_up_path, class: "space-y-8" do |form| %>
        <div class="space-y-2">
          <%= form.label :name, t(".account_name"), class: "block text-sm font-medium text-gray-700" %>
          <div class="mt-1">
            <%= form.text_field :name, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" %>
          </div>
        </div>

        <div class="space-y-2">
          <%= form.label :subdomain, t(".subdomain"), class: "block text-sm font-medium text-gray-700" %>
          <div class="mt-1 flex">
            <%= form.text_field :subdomain, class: "flex-1 min-w-0 block w-full px-3 py-2 rounded-none rounded-l-md focus:ring-blue-500 focus:border-blue-500 sm:text-sm border-gray-300", placeholder: "acme-golf" %>
            <span class="inline-flex items-center px-2 rounded-r-md border border-l-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm"> .albatrosscms.com </span>
          </div>
        </div>

        <div>
          <%= form.submit t(".submit"), class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
        </div>
      <% end %>
    </div>
  </div>

  <%= render "shared/error_messages", resource: @account %>
</div>

app/views/marketing/accounts/new.html.erb
<div class="max-w-5xl mx-auto">
  <%= render "form", account: @account %>
</div>